### ISSUE TITLE
Feature: Connect to #hackerspace channel on Slack

### ISSUE THREAD

**Issue by jeff-arn** [hackmanhattan/defaultcast#1]
I'd like to open a PR that implements the following:

- [ ] websockets within the python backend
- [ ] websockets in JS on frontend
- [ ] Slack API integration on python backend

This way, we can push new messages to the frontend without polling. Consider this assigned to me, and lemme know if you are ok with this. I can push changes into a new branch.

**Comment by eaon** [comment]
Sounds good to me. I guess there would be overlap with https://github.com/hackmanhattan/hmbot - I mean, hmbot doesn't need to be the host of the websocket backend, but at least forward the messages to it.

**Comment by eaon** [comment]
@guanix helped close this one with his new bah (bah ain't hmbot) bot
